Added deploy compilation mode for grunt.
Default mode was executing  as well, so building wouldn't finish on our CI system (jenkins).
That required manually pulling and replacing Gruntfiles, and keeping them up to date.

Now we can simly use A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile. for necessary compilations only.